# Regularization parameters
lambda_L: 0.6
lambda_H: 0.3
lambda_param_L: 0.2
lambda_param_H: 0.1

# Optimization parameters
eta_max: 0.001
eta_min: 0.001
max_iter: 2000
num_steps_min: 5
num_steps_max: 2
tol: 0.0001

# K-Fold Cross-Validation settings
k_folds: 2

seed: 23 # 42             # For all random operations, including KFold
plot_steps: false
plot_epochs: false
display_results: false

# Method flags
xavier: false
project_onto_gelbrich: true
proximal_grad: true
grad_clip: true
robust_L: true
robust_H: true