eta_max: 0.001
eta_min: 0.001

max_iter: 5000
num_steps_min: 5
num_steps_max: 2
tol: 0.0001

# K-Fold Cross-Validation settings
k_folds: 5

seed: 23 # 42
robust_L: true 
robust_H: true

initialization: 'random'

