model_type: 'continuous_nonlinear_anm'
experiment_name: 'nonlinlucas'

num_llsamples: 10000
num_hlsamples: 10000

# Low-Level (LL) Model Definition
low_level_model:
  # NOTE: Variable names must be valid Python identifiers (no spaces)
  variables: ['Smoking', 'Genetics', 'Lung_Cancer', 'Allergy', 'Coughing', 'Fatigue']

  # The graph structure must be defined explicitly for non-linear models
  graph_edges:
    - ['Smoking', 'Lung_Cancer']
    - ['Genetics', 'Lung_Cancer']
    - ['Lung_Cancer', 'Coughing']
    - ['Allergy', 'Coughing']
    - ['Lung_Cancer', 'Fatigue']
    - ['Coughing', 'Fatigue']

  # Non-linear functions are defined as strings
  structural_functions:
    # Root nodes are functions with no arguments
    'Smoking': "lambda: 0"
    'Genetics': "lambda: 0"
    'Allergy': "lambda: 0"
    # Child nodes are functions of their parents
    'Lung_Cancer': "lambda Smoking, Genetics: 0.9 * np.abs(Smoking)**1.2 + 0.8 * np.sin(Genetics * 3)"
    'Coughing': "lambda Lung_Cancer, Allergy: 0.6 * np.tanh(Lung_Cancer) + 0.4 * Allergy"
    'Fatigue': "lambda Lung_Cancer, Coughing: 0.9 * Lung_Cancer + 0.5 * Coughing**2"

  noise_params:
    mu: [0, 0, 0.1, 0.1, 0.3, 0.2]
    sigma_diag: [0.5, 2.0, 1.0, 1.5, 0.8, 1.2]

# High-Level (HL) Model Definition (for the inferred linear model)
high_level_model:
  variables: ['Environment', 'Genetics_', 'Lung_Cancer_']
  initial_coefficients:
    - [['Environment', 'Lung_Cancer_'], 0.0]
    - [['Genetics_', 'Lung_Cancer_'], 0.0]

# Abstraction Definition
abstraction:
  # The T matrix for mapping LL -> HL
  T_matrix:
    - [2, 1, 1, 0.5, 1, 0.5]
    - [0.5, 2, 0.8, 1.5, 0.7, 1]
    - [1, 0.5, 1, 2, 0.9, 1.5]
  
  # Definitions for all interventions
  interventions:
    # Low-level interventions
    iota0: 'None'
    iota1: {'Smoking': 0}
    iota2: {'Smoking': 1}
    iota3: {'Lung_Cancer': 0}
    iota4: {'Lung_Cancer': 1}
    iota5: {'Smoking': 0, 'Lung_Cancer': 0}
    iota6: {'Smoking': 1, 'Lung_Cancer': 1}
    iota7: {'Smoking': 0, 'Lung_Cancer': 1}
    iota8: {'Smoking': 1, 'Lung_Cancer': 0}
    iota9: {'Genetics': 0}
    iota10: {'Genetics': 1}
    iota11: {'Genetics': 0, 'Smoking': 0}
    iota12: {'Genetics': 1, 'Smoking': 1}
    iota13: {'Genetics': 0, 'Smoking': 1}
    iota14: {'Genetics': 1, 'Smoking': 0}
    iota15: {'Allergy': 0}
    iota16: {'Allergy': 1}
    iota17: {'Coughing': 0}
    iota18: {'Coughing': 1, 'Fatigue': 1}
    iota19: {'Coughing': 1, 'Fatigue': 0}
    iota20: {'Coughing': 0, 'Fatigue': 1}
    # High-level interventions
    eta0: 'None'
    eta1: {'Environment': 0}
    eta2: {'Environment': 1}
    eta3: {'Genetics_': 0}
    eta4: {'Genetics_': 1}
    eta5: {'Environment': 0, 'Genetics_': 0}
    eta6: {'Environment': 1, 'Genetics_': 1}
    eta7: {'Environment': 0, 'Genetics_': 1}
    eta8: {'Environment': 1, 'Genetics_': 0}
    eta9: {'Lung_Cancer_': 0}
    eta10: {'Lung_Cancer_': 1}

  # The omega map, mapping LL intervention names to HL intervention names
  omega_map:
    iota0: 'eta0'
    iota1: 'eta1'
    iota2: 'eta2'
    iota3: 'eta3'
    iota4: 'eta4'
    iota5: 'eta5'
    iota6: 'eta6'
    iota7: 'eta9'
    iota8: 'eta10'
    iota10: 'eta5'
    iota11: 'eta6'
    iota12: 'eta3'
    iota13: 'eta4'
    iota14: 'eta8'
    iota15: 'eta7'
    iota16: 'eta5'
    iota17: 'eta6'
    iota18: 'eta10'
    iota19: 'eta9'
    iota20: 'eta8'